const DogBreed = [
    { id: 0, value: '비글', code: 'BEA' },
    { id: 1, value: '비숑프리제', code: 'BIC' },
    { id: 2, value: '불독', code: 'BUL' },
    { id: 3, value: '치와와 장모', code: 'CHL' },
    { id: 4, value: '치와와 단모', code: 'CHS' },
    { id: 5, value: '코커스패니엘', code: 'COC' },
    { id: 6, value: '닥스훈트 장모', code: 'DAL' },
    { id: 7, value: '닥스훈트 단모', code: 'DAS' },
    { id: 8, value: '도베르만핀셔', code: 'DOB' },
    { id: 9, value: '시추', code: 'DRI' },
    { id: 10, value: '기타', code: 'ETC' },
    { id: 11, value: '저먼 셰퍼드', code: 'GER' },
    { id: 12, value: '골든 리트리버', code: 'GOL' },
    { id: 13, value: '그레이트피레니즈', code: 'GRE' },
    { id: 14, value: '하운드', code: 'HOU' },
    { id: 15, value: '허스키', code: 'HUS' },
    { id: 16, value: '진돗개', code: 'JIN' },
    { id: 17, value: '래브라도 리트리버', code: 'LAB' },
    { id: 18, value: '몰티즈', code: 'MAL' },
    { id: 19, value: '믹스 장모', code: 'MIL' },
    { id: 20, value: '믹스 단모', code: 'MIS' },
    { id: 21, value: '말라뮤트', code: 'MUT' },
    { id: 22, value: '포메라니안', code: 'POM' },
    { id: 23, value: '푸들 미니어처', code: 'POO' },
    { id: 24, value: '슈나우저', code: 'SCH' },
    { id: 25, value: '쉽독', code: 'SHE' },
    { id: 26, value: '테리어', code: 'TER' },
    { id: 27, value: '웰시코기', code: 'WEL' },
];

export default DogBreed;
